name: climakitae-tests

channels:
  - conda-forge
dependencies:
  - python
  - cartopy
  - geopandas
  - geoviews
  - holoviews
  - hvplot
  - intake
  - intake-geopandas
  - intake-xarray
  - intake-esm
  - jinja2
  - matplotlib
  - metpy
  - numpy
  - pandas
  - panel
  - param
  - proj
  - psutil
  - pyproj
  - pytest
  - rioxarray
  - s3fs
  - scipy
  - shapely
  - xarray
  - xmip
  - pygeos
  - pip
    - dask-gateway
    - dask-geopandas
    - xclim
