name: climakitae-tests

channels:
  - conda-forge
dependencies:
  - python
  - boltons
  - lmoments3
  - jsonpickle
  - llvmlite
  - bottleneck
  - boto3
  - tqdm
  - pydantic
  - pyarrow
  - xarray
  - dask
  - cartopy
  - geopandas
  - intake
  - intake-geopandas
  - intake-xarray
  - intake-esm
  - jinja2
  - matplotlib
  - metpy
  - numpy
  - pandas
  - param
  - psutil
  - pyproj
  - pytest
  - rioxarray
  - s3fs
  - scipy
  - shapely
  - pygeos
  - statsmodels
  - markupsafe
  - webob
  - affine
  - asciitree
  - attrs
  - beautifulsoup4
  - certifi
  - cffi
  - cfgrib
  - cftime
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - docopt
  - eccodes
  - fasteners
  - findlibs
  - fsspec
  - h5netcdf
  - h5py
  - idna
  - importlib-metadata
  - importlib-resources
  - lxml
  - netcdf4
  - numcodecs
  - platformdirs
  - pooch
  - pycparser
  - pydap
  - pyparsing
  - rasterio
  - requests
  - soupsieve
  - urllib3
  - zarr
  - zipp
  - pip
  - pip:
    - numba
    - timezonefinder
    - dask-gateway
    - dask-geopandas
    - xclim
